name: bva_parking
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  grouped_buttons: ^1.0.4
  cloud_firestore: ^0.13.7
  fluttertoast: ^4.0.1
  url_launcher: ^5.4.11
  intent:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
